dist: focal
sudo: required
language: java
jdk:
  - openjdk17

# the cache can grow constantly
before_cache:
  - rm -rf $HOME/.m2/repository/org/alfresco/cmis/client/alfresco-opencmis-extension
cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - master
    - /support\/.*/

stages:
  - test
  - release

install:
  - "cp .travis.settings.xml $HOME/.m2/settings.xml"
  - travis_retry mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

jobs:
  include:
    - stage: test
    - name: "Default Job"
      script: travis_wait 40 mvn --batch-mode -U clean org.jacoco:jacoco-maven-plugin:prepare-agent install
    - stage: release
      name: "Push to Nexus"
      if: fork = false AND (branch = master OR branch =~ /support\/.*/) AND type != pull_request AND commit_message !~ /\[no-release\]/
      before_install:
      script:
        # Use full history for release
        - git checkout -B "${TRAVIS_BRANCH}"
        # Add email to link commits to user
        - git config user.email "${GIT_EMAIL}"
        # Skip building of release commits
        - mvn --batch-mode -q -DscmCommentPrefix="[maven-release-plugin][skip ci] " -Dusername="${GIT_USERNAME}" -Dpassword="${GIT_PASSWORD}" -DskipTests -Darguments=-DskipTests release:clean release:prepare release:perform
